-- ⚠️ OBSOLETO — NÃO APLICAR.
--
-- Este ficheiro era a cópia para o SQL Editor da migração
-- `20260927090000_plan_entitlements.sql`. Continha os preços ANTIGOS
-- (Free 0; Starter 19; Pro 39) e usava `max_searches_month = -1` como
-- "ilimitado" (que viola a constraint `plans_searches_check`) e
-- `coalesce(max_searches_month, 50)` (que limitaria o Pro a 50).
--
-- Foi substituído por:
--   * `supabase/migrations/20260927090000_plan_entitlements.sql` (estrutura)
--   * `supabase/migrations/20260928090000_plan_pricing_v2.sql` + cópia
--     `SUPABASE_PLAN_ENTITLEMENTS_20260928.sql` (fonte única atual).
--
-- Aplicar este ficheiro por engano REVERTERIA os preços em produção para os
-- valores antigos. Mantido apenas como referência histórica.

