import type { Metadata } from "next";
import PublicPage from "@/components/PublicPage";
import { legalOperator } from "@/lib/legal";

export const metadata: Metadata = { title: "Termos de utilização", description: "Termos de utilização do Radar B2B." };

export default function TermsPage() {
  return <PublicPage><article className="prose prose-invert max-w-3xl prose-headings:font-semibold prose-headings:tracking-tight prose-headings:text-white prose-p:text-slate-400 prose-li:text-slate-400"><p className="not-prose text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">Condições</p><h1>Termos de utilização</h1><p className="lead">Última atualização: 17 de setembro de 2026</p><p>Estes termos regulam o acesso ao Radar B2B, uma plataforma de pesquisa e análise de informação pública sobre contratação pública.</p><h2>1. Operador e contacto</h2><p><strong>Entidade responsável:</strong> {legalOperator.name}, {legalOperator.legalForm}, {legalOperator.country}.<br /><strong>Morada e contacto:</strong> serão publicados após confirmação da designação legal definitiva.</p><h2>2. Utilização permitida</h2><p>O utilizador deve fornecer informação verdadeira, manter as credenciais seguras e utilizar o serviço de forma lícita. Não é permitido contornar quotas, aceder a contas de terceiros, extrair dados por meios abusivos ou interferir com o serviço.</p><h2>3. Dados e limitações</h2><p>Os dados têm origem em fontes públicas e podem conter omissões, atrasos ou erros. A referência oficial prevalece sempre. O Radar B2B não garante adjudicação, elegibilidade, disponibilidade de documentos ou atualização instantânea.</p><h2>4. Conta, planos e pagamento</h2><p>Algumas funcionalidades dependem de autenticação, quota e plano. Os pagamentos e a gestão da subscrição são processados pelo fornecedor de faturação indicado no produto.</p><h2>5. Alterações</h2><p>Estes termos podem ser atualizados por motivos de segurança, evolução do serviço ou obrigações legais. A versão aplicável será a publicada nesta página.</p></article></PublicPage>;
}
