import type { Metadata } from "next";
import PublicPage from "@/components/PublicPage";
import { legalOperator } from "@/lib/legal";

export const metadata: Metadata = { title: "Política de privacidade", description: "Como o Radar B2B trata dados pessoais e assegura os direitos dos titulares." };

export default function PrivacyPage() {
  return <PublicPage><article className="prose prose-invert max-w-3xl prose-headings:font-semibold prose-headings:tracking-tight prose-headings:text-white prose-p:text-slate-400 prose-li:text-slate-400"><p className="not-prose text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">RGPD</p><h1>Política de privacidade</h1><p className="lead">Última atualização: 17 de setembro de 2026</p><p>Esta política explica como o Radar B2B trata dados pessoais. A designação comercial definitiva e os dados legais de contacto serão publicados antes da disponibilização comercial do serviço.</p><h2>1. Responsável pelo tratamento</h2><p><strong>Responsável:</strong> {legalOperator.name}, {legalOperator.legalForm}, estabelecido em {legalOperator.country}.<br /><strong>Morada e contacto de privacidade:</strong> pendentes de publicação com a designação legal definitiva.<br /><strong>DPO:</strong> pendente de avaliação de aplicabilidade.</p><h2>2. Dados tratados</h2><ul><li>Dados de conta, como email e identificadores de utilizador.</li><li>Dados de utilização necessários para quotas, segurança e suporte.</li><li>Pesquisas, oportunidades e alertas guardados pelo utilizador.</li><li>Dados técnicos mínimos de segurança e diagnóstico.</li></ul><h2>3. Finalidades e bases legais</h2><p>Os dados são tratados para prestar o serviço, gerir contas, prevenir abuso, responder a pedidos de suporte e cumprir obrigações legais. Quando aplicável, as comunicações opcionais dependem de consentimento.</p><h2>4. Conservação e segurança</h2><p>Os dados são conservados apenas pelo período necessário para as finalidades indicadas e obrigações legais. O acesso é protegido por autenticação, permissões e controlos técnicos adequados.</p><h2>5. Direitos dos titulares</h2><p>Podes pedir acesso, retificação, apagamento, limitação, oposição ou portabilidade através do canal de suporte publicado no produto quando a identidade legal definitiva for confirmada.</p></article></PublicPage>;
}
