import type { Metadata } from "next";
import PublicPage from "@/components/PublicPage";
import { legalOperator } from "@/lib/legal";

export const metadata: Metadata = { title: "Política de privacidade", description: "Como o Radar B2B trata dados pessoais e assegura os direitos dos titulares." };

export default function PrivacyPage() {
  return <PublicPage><article className="prose prose-invert max-w-3xl prose-headings:font-semibold prose-headings:tracking-tight prose-headings:text-white prose-p:text-slate-400 prose-li:text-slate-400"><p className="not-prose text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">RGPD</p><h1>Política de privacidade</h1><p className="lead">Última atualização: 16 de setembro de 2026</p><p>Esta política explica como o operador do Radar B2B trata dados pessoais. A morada de residência do ENI não é apresentada no footer nem usada para marketing; será fornecida às autoridades ou titulares quando exista obrigação legal ou pedido legítimo.</p><h2>1. Responsável pelo tratamento</h2><p><strong>Responsável:</strong> {legalOperator.name}, {legalOperator.legalForm}, NIF {legalOperator.nif}, estabelecido em {legalOperator.country}.<br /><strong>Morada:</strong> pendente de decisão sobre a forma legal de divulgação.<br /><strong>Contacto de privacidade:</strong> pendente.<br /><strong>DPO:</strong> pendente de avaliação de aplicabilidade.</p><h2>2. Dados tratados</h2><ul><li>Dados de conta, como email e identificadores de utilizador.</li><li>Dados de utilização necessários para quotas, segurança e suporte.</li><li>Pesquisas, oportunidades e alertas guardados pelo utilizador.</li><li>Dados técnicos mínimos de segurança e diagnóstico.</li></ul><p>Não deves inserir categorias especiais de dados ou informação de terceiros que não seja necessária para a finalidade da funcionalidade.</p><h2>3. Finalidades e bases legais</h2><p>Prestação do serviço e gestão da conta: execução do contrato. Segurança, prevenção de abuso e registos técnicos: interesse legítimo, ponderado com os direitos do titular. Comunicações opcionais e cookies não necessários: consentimento. Obrigações legais: cumprimento de obrigação jurídica.</p><h2>4. Partilha e subcontratantes</h2><p>O serviço pode recorrer a fornecedores de alojamento, base de dados, autenticação, observabilidade e faturação. O operador deve manter uma lista atualizada de subcontratantes, contratos, localizações e garantias de transferência internacional.</p><h2>5. Conservação</h2><p>Os dados são conservados apenas pelo tempo necessário à finalidade, relação contratual, segurança e cumprimento de obrigações legais. Os prazos concretos devem ser definidos pelo operador no registo de tratamento.</p><h2>6. Direitos</h2><p>Podes pedir acesso, retificação, apagamento, limitação, oposição e portabilidade quando aplicável. Podes retirar consentimento a qualquer momento. Também podes apresentar reclamação à Comissão Nacional de Proteção de Dados.</p><h2>7. Segurança e incidentes</h2><p>O operador deve aplicar controlo de acessos, RLS no Supabase, gestão de segredos, backups, minimização e um procedimento documentado de resposta a incidentes. Incidentes com risco devem ser avaliados e comunicados nos prazos legais.</p></article></PublicPage>;
}
